// ABIs are generated by apps/contracts deploy script and copied here
export const PantheonVaultABI: unknown[] = [];
export const PantheonRegistryABI: unknown[] = [];
export const TraceAnchorABI: unknown[] = [];
