/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPantheonRegistryView } from "./IPantheonRegistryView";
export type { TraceAnchor } from "./TraceAnchor";
